<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuizQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Apa kepanjangan dari SIM?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Surat Izin Mengemudi'],
                    ['id' => 'B', 'teks' => 'Surat Izin Motor'],
                    ['id' => 'C', 'teks' => 'Surat Identitas Mengemudi'],
                ]),
                'jawaban' => 'A',
                'penjelasan' => 'SIM adalah Surat Izin Mengemudi, bukti registrasi dan identifikasi yang diberikan oleh Polri.',
                'pasal' => 'Pasal 77 UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Berapa batas usia minimal untuk memiliki SIM C?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => '16 Tahun'],
                    ['id' => 'B', 'teks' => '17 Tahun'],
                    ['id' => 'C', 'teks' => '18 Tahun'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Batas usia minimal untuk memiliki SIM C (sepeda motor) adalah 17 tahun.',
                'pasal' => 'Pasal 81 UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Apa fungsi utama dari zebra cross?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Tempat parkir motor'],
                    ['id' => 'B', 'teks' => 'Tempat pejalan kaki menyeberang'],
                    ['id' => 'C', 'teks' => 'Tempat putar balik'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Zebra cross adalah tempat penyeberangan pejalan kaki yang dinyatakan dengan marka jalan.',
                'pasal' => 'Fasilitas Pejalan Kaki',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Rambu dengan warna dasar merah dan tulisan putih biasanya merupakan rambu...',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Petunjuk'],
                    ['id' => 'B', 'teks' => 'Peringatan'],
                    ['id' => 'C', 'teks' => 'Larangan'],
                ]),
                'jawaban' => 'C',
                'penjelasan' => 'Warna dasar merah dengan lambang/tulisan putih/hitam adalah karakteristik rambu larangan.',
                'pasal' => 'Permenhub tentang Rambu',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Apa hukuman mengendarai motor tanpa helm SNI?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Denda maksimal Rp250.000 atau kurungan 1 bulan'],
                    ['id' => 'B', 'teks' => 'Hanya ditegur oleh Polisi'],
                    ['id' => 'C', 'teks' => 'Motor disita'],
                ]),
                'jawaban' => 'A',
                'penjelasan' => 'Pengendara dan penumpang yang tidak mengenakan helm SNI dipidana kurungan paling lama 1 bulan atau denda paling banyak Rp250.000.',
                'pasal' => 'Pasal 291 ayat (1) UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Marka jalan berwarna kuning membujur tanpa putus di tengah jalan berarti...',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Boleh mendahului'],
                    ['id' => 'B', 'teks' => 'Jalan nasional dan dilarang melintasi garis'],
                    ['id' => 'C', 'teks' => 'Batas kecepatan'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Garis kuning membujur utuh merupakan batas lajur jalan nasional dan pengemudi dilarang melintasinya.',
                'pasal' => 'Permenhub Marka Jalan',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Jika terjadi kecelakaan, apa kewajiban pertama pengemudi?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Melarikan diri agar tidak dihakimi massa'],
                    ['id' => 'B', 'teks' => 'Berhenti, menolong korban, dan lapor polisi'],
                    ['id' => 'C', 'teks' => 'Membiarkan saja karena bukan salahnya'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Pengemudi yang terlibat kecelakaan lalu lintas wajib menghentikan kendaraan, menolong korban, dan melapor ke Polri.',
                'pasal' => 'Pasal 231 UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Apa fungsi dari lampu Hazard?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Memberi tanda saat hujan deras'],
                    ['id' => 'B', 'teks' => 'Tanda keadaan darurat saat berhenti'],
                    ['id' => 'C', 'teks' => 'Tanda rombongan konvoi'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Lampu isyarat peringatan bahaya (hazard) hanya digunakan saat kendaraan berhenti karena keadaan darurat.',
                'pasal' => 'Pasal 121 UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Berapa kecepatan maksimal di kawasan permukiman?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => '30 km/jam'],
                    ['id' => 'B', 'teks' => '50 km/jam'],
                    ['id' => 'C', 'teks' => '60 km/jam'],
                ]),
                'jawaban' => 'A',
                'penjelasan' => 'Kecepatan maksimal pada jalan lingkungan/permukiman adalah 30 km/jam demi keselamatan bersama.',
                'pasal' => 'PP No. 79 Tahun 2013',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Apa yang harus dilakukan saat mendengar sirine pemadam kebakaran?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Merapat ke tepi jalan dan memberi prioritas jalan'],
                    ['id' => 'B', 'teks' => 'Melaju lebih cepat agar tidak tertinggal'],
                    ['id' => 'C', 'teks' => 'Abaikan saja'],
                ]),
                'jawaban' => 'A',
                'penjelasan' => 'Pemadam kebakaran yang sedang bertugas adalah pengguna jalan yang mendapat prioritas nomor satu (1).',
                'pasal' => 'Pasal 134 UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Selain SIM dan STNK, kelengkapan apa yang wajib dibawa?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'KTP'],
                    ['id' => 'B', 'teks' => 'BPKB'],
                    ['id' => 'C', 'teks' => 'Helm SNI'],
                ]),
                'jawaban' => 'A',
                'penjelasan' => 'Sebagai WNI, KTP adalah identitas wajib. Untuk pengemudian, SIM, STNK, dan kelengkapan standar kendaraan wajib ada.',
                'pasal' => 'Pasal 106 ayat (5) UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Di mana posisi berjalan kaki yang benar jika tidak ada trotoar?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Di tengah jalan'],
                    ['id' => 'B', 'teks' => 'Di sebelah paling kanan (menghadap arus lalu lintas)'],
                    ['id' => 'C', 'teks' => 'Di sebelah kiri (searah arus)'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Jika tidak ada trotoar, pejalan kaki wajib berjalan di tepi jalan menghadap arus kendaraan untuk keamanan visual.',
                'pasal' => 'Pasal 132 UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Kendaraan bermotor wajib menyalakan lampu utama pada siang hari untuk...',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Mobil penumpang'],
                    ['id' => 'B', 'teks' => 'Sepeda motor'],
                    ['id' => 'C', 'teks' => 'Truk barang'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Pengendara sepeda motor wajib menyalakan lampu utama pada siang hari (Light On) agar lebih terlihat oleh pengemudi lain.',
                'pasal' => 'Pasal 107 ayat (2) UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Apa yang dilarang saat berada di jalan tol?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Berjalan dengan kecepatan 80 km/jam'],
                    ['id' => 'B', 'teks' => 'Menaikkan atau menurunkan penumpang'],
                    ['id' => 'C', 'teks' => 'Menyalip dari sebelah kanan'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Jalan tol adalah jalan bebas hambatan. Dilarang menaikkan/menurunkan penumpang di jalan tol karena sangat berbahaya.',
                'pasal' => 'PP tentang Jalan Tol',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Lampu kuning berkedip pada simpang jalan berarti...',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Berhenti dan tunggu hijau'],
                    ['id' => 'B', 'teks' => 'Jalan terus secepatnya'],
                    ['id' => 'C', 'teks' => 'Hati-hati dan kurangi kecepatan'],
                ]),
                'jawaban' => 'C',
                'penjelasan' => 'Isyarat lampu kuning berkedip (flashing yellow) memperingatkan pengemudi untuk berhati-hati dan mengurangi kecepatan.',
                'pasal' => 'Aturan Rambu Bersinyal',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Kapan plat nomor (TNKB) harus diganti baru?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Setiap 1 tahun'],
                    ['id' => 'B', 'teks' => 'Setiap 5 tahun'],
                    ['id' => 'C', 'teks' => 'Setiap ganti oli'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'TNKB dan STNK berlaku selama 5 tahun, yang harus dimintakan pengesahan setiap tahun.',
                'pasal' => 'Pasal 70 UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Berapa banyak orang yang boleh dibonceng pada sepeda motor?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Maksimal 1 orang'],
                    ['id' => 'B', 'teks' => 'Maksimal 2 orang jika muat'],
                    ['id' => 'C', 'teks' => 'Tidak dibatasi'],
                ]),
                'jawaban' => 'A',
                'penjelasan' => 'Sepeda motor hanya diperbolehkan untuk membawa paling banyak 1 (satu) orang penumpang.',
                'pasal' => 'Pasal 106 ayat (9) UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Apa arti rambu berbentuk lingkaran dengan latar biru dan gambar panah lurus?',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Larangan berjalan lurus'],
                    ['id' => 'B', 'teks' => 'Perintah berjalan lurus'],
                    ['id' => 'C', 'teks' => 'Petunjuk arah'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Rambu dengan latar biru dan bentuk lingkaran adalah rambu perintah. Panah lurus berarti wajib lurus.',
                'pasal' => 'Permenhub tentang Rambu',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Alat pemantul cahaya tambahan pada bagian belakang truk berfungsi untuk...',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Estetika kendaraan'],
                    ['id' => 'B', 'teks' => 'Mempermudah terlihat di malam hari'],
                    ['id' => 'C', 'teks' => 'Penanda perusahaan'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Reflektor/alat pemantul cahaya wajib pada kendaraan besar untuk meminimalisir tabrak belakang di malam hari.',
                'pasal' => 'Peraturan Keselamatan Kendaraan',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'gambar' => 'https://placehold.co/600x400/png?text=Gambar+Kuis',
                'situasi' => 'Mengemudi di bawah pengaruh alkohol diancam dengan hukuman...',
                'pilihan' => json_encode([
                    ['id' => 'A', 'teks' => 'Tilang Rp100.000'],
                    ['id' => 'B', 'teks' => 'Denda maksimal Rp3.000.000 atau kurungan 1 tahun'],
                    ['id' => 'C', 'teks' => 'Kerja bakti sosial'],
                ]),
                'jawaban' => 'B',
                'penjelasan' => 'Mengemudikan kendaraan secara tidak wajar atau dalam keadaan mabuk dipidana kurungan paling lama 1 tahun atau denda maksimal Rp3.000.000.',
                'pasal' => 'Pasal 311 UU 22/2009',
                'poin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('quiz_questions')->insert($questions);
    }
}
